# Generated by Django 4.2.30 on 2026-05-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignUpSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("parent_name", models.CharField(max_length=200)),
                ("grade", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("prior_cad_knowledge", models.TextField(blank=True)),
                ("why_join", models.TextField()),
                (
                    "submitted_from_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
